services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /Users/benmayo/.gcp/keys/ngl-local-dev.json:/secrets/sa.json:ro
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/sa.json
      - SECRET_MANAGER_PROJECT=ngl-project-2025
